application: gae-mr-example
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# task to populate the db with entities we want to iterate over
- url: /populate_db
  script: tasks.app

# task that starts the magic of mapreduce
- url: /start_job
  script: tasks.app

# the map reduce handler, this handles the inner calls of mapreduce
- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
